services:
    nginx:
        build: .
        ports:
            - "80:80"
        volumes:
            - .:/app
            - .docker/nginx-images-cache/:/tmp/nginx-images-cache
    client:
        image: node:20.16-bookworm-slim
        ports:
            - "5175:5175"
        volumes:
            - .:/app
        working_dir: /app
        command: bash -c "npm install && npm run dev"
